### PR TITLE
Upgrade the library to use Cucumber's latest package

### PR DESCRIPTION
**Pull request by sroze**
As discussed in https://github.com/cucumber/cucumber-js/issues/1369, a pre-release for `cucumber-js` (package renamed `@cucumber/cucumber`) has been released.

This pull-request proposes to release a new major version of this one, using this new package.

### CODE REVIEW

**Comment by sroze** [comment]
👋 @timjroberts would you have some time to look at this PR?

**Comment by sroze** [comment]
Or maybe @wudong as you have been pushing most of the updates recently?

**Comment by wudong** [comment]
yeah, will do this weekend.

**Comment by sroze** [comment]
Thank you 🙌

**Comment by wudong** [comment]
Hi Sroze, thanks for the PR, I have merge it now but will wait for cucumber 7.0.0 to become official to do a full release of tsflow.

**Comment by sroze** [comment]
That’s great, thank you @wudong. Do you mind making a release candidate like they did for cucumber so I can try on a few projects to validate it works well? 👌

**Pull request merged**
