### PR TITLE
Add named exports

### PR DESCRIPTION
**Pull request by cjmarkham**
Adds named exports

Resolves https://github.com/timjroberts/cucumber-js-tsflow/issues/146

### CODE REVIEW

**Review by Fryuni — COMMENTED** [review]
Each test scenario creates an entire node package to run the test on. Can you add a new scenario creating a package with `"type": "module"` or with `.mts` files to demonstrate the issue and ensure we don't get a regression in the future?

**Comment by cjmarkham** [comment]
> Each test scenario creates an entire node package to run the test on. Can you add a new scenario creating a package with `"type": "module"` or with `.mts` files to demonstrate the issue and ensure we don't get a regression in the future?

It's a bit more involved than adding an `mts` file. We'd need to add a new runner since it would require the `import` flag, rather than `require`.

We'd also need to add experimental node features to load the `.mts` files.

I can do the above, but it's going to take a while longer to do so.

**Comment by cjmarkham** [comment]
We'd also need to add the new runner to the `CucumberSteps` class, or duplicate it so we have 2 versions, one for each runner....

**Comment by cjmarkham** [comment]
I've tested the changes required and there's a lot of them, and a lot of duplication too. 

I'd suggest we close this since we can't realistically add a test for it without huge changes.

We could, however, create version 5 of this package which is an ESM module....

I'll leave the decision to close this to you.

**Comment by Fryuni** [comment]
It doesn't seem to me like it would need many changes, only wiring on `runner.ts` and `prepare.ts`.

We could have this in the root `package.json`:
```json
{
  "scripts": {
    "test": "npm run test:cjs && npm run test:esm",
    "test:base": "cucumber-js -p default cucumber-tsflow-specs/features/**/*.feature",
    "test:cjs": "CUCUMBER_PACKAGE_MODE=cjs npm run test:base",
    "test:esm": "CUCUMBER_PACKAGE_MODE=esm npm run test:base"
  }
}
```

And have those two files react to it that env var accordingly, so every test would run for both CJS and ESM.

Currently, all the projects I'm running using Cucumber and this lib are CJS packages (which amounts to dozens of libraries and services), so I have no intention of dropping support for it in the foreseeable future. But I'm OK with adding support for ESM as long as we can have tests for it.

**Comment by Fryuni** [comment]
I haven't ever used Cucumber with an ESM package/service, so I don't even know how to set it up.

**Comment by cjmarkham** [comment]
I'll see about putting something together tomorrow .

**Comment by cjmarkham** [comment]
I've tried but it's quite a complex thing just for named exports.

We would need to add a custom loader to intercept the load of `cucumber-js` and use `cucumber.js` instead. TSNode doesn't like files without extensions.

We also run in to the issue where we have to use the experimental loaders and resolutions. Because of these, we either need to specify `type:"module"`, or have `mts` files for everything.

I'd suggest we close this. Named exports was just a nice little improvement but the changes needed to add tests around it alter the package significantly.

**Comment by Fryuni** [comment]
Ok then, thanks for exploring that!

**Pull request closed without merging**
