### PR TITLE
A combined PR to address a few issues

### PR DESCRIPTION
**Pull request by wudong**
* Remove the behaviour of prepending @ to tag. #45 
* Add passing wrapperOptions to cucumber.js #68 #42
* Add timeout support for hooks #72 
* Add run config for IntelliJ/Webstorm
* Update readme.
* Add a Contribute.md guild for debug in IDE. #38

### CODE REVIEW

**Comment by x80486** [comment]
Is there anything outstanding for this one?

**Comment by cortopy** [comment]
would it be possible to merge this one? timeout on @before/@after would be great

**Comment by bryant-svedin-gehc** [comment]
I would also like this one to merge. I want timeout on before/after

**Comment by Fryuni** [comment]
Hey @bryant-svedin-gehc, thanks for bringing this up.

Some of the changes on this PR have already landed separately, so you might want to check the latest rc. I'll have a look into adding a step-specific timeout accounting for the new changes.

**Comment by bryant-svedin-gehc** [comment]
I am using 
"cucumber-tsflow": "^4.0.0-rc.7"
It does not appear to be able to set the timeout in before/after 
I can set timeout in given, when, then steps
I would like to have timeout on before/after

Also, are there plans for a beforeFeature/afterFeature or could be called beforeAll/afterAll?
The current before/after run with each scenario
It would be nice to be able to have some configuration/cleanup run only once with the entire feature

**Comment by Fryuni** [comment]
@wudong I just merged this with some changes:

- Step and hook options are passed as an object to prevent the `undefined, undefined, {...}`
  For compatibility, the existing signatures also works
- Since I had previous changed the logic of the tags to support both the old tag names and the new tag expressions I dropped this part of your PR

@bryant-svedin-gehc The new signature is [on the README](https://github.com/timjroberts/cucumber-js-tsflow#hooks)

I'll check #51 for the `beforeAll`/`afterAll` support. I'll cut a new RC later today, if I can fix on that PR and get it merged before that you'll be able to test both, otherwise I'll cut another RC monday (maybe).

With these changes in place I'll add some more tests for them and if everything is stable I'll cut a proper v4 release

**Pull request merged**
